from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path
from statistics import mean
from typing import Any

from evigraph.failure_analysis import FailureAnalyzer
from evigraph.row_operation_diagnostics import DIAGNOSTIC_LABELS, RowOperationDiagnosticAnalyzer


@dataclass(frozen=True)
class ResultSpec:
    label: str
    csv_name: str
    methods: tuple[str, ...]


DEFAULT_RESULT_SPECS = (
    ResultSpec(
        "Oracle-doc",
        "finqa_subset_oracle_doc_ablation.csv",
        ("topk", "utility_only", "full_evigraph"),
    ),
    ResultSpec(
        "Open BM25",
        "finqa_subset_open_bm25_ablation.csv",
        ("topk", "utility_only", "full_evigraph"),
    ),
    ResultSpec(
        "Open hybrid",
        "finqa_subset_open_hybrid_ablation.csv",
        ("topk", "utility_only", "full_evigraph"),
    ),
    ResultSpec(
        "BM25 + source rerank",
        "finqa_subset_source_rerank_ablation.csv",
        ("topk", "utility_only", "full_evigraph"),
    ),
)


class PaperAssetBuilder:
    """Build paper-ready result snippets from manifest CSV outputs."""

    def build(self, eval_dir: str | Path, output_dir: str | Path) -> dict[str, str]:
        eval_path = Path(eval_dir)
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        result_rows = self._result_rows(eval_path)
        failure_rows = self._failure_rows(eval_path)
        diagnostic_rows = self._diagnostic_rows(eval_path)
        paths = {
            "latex": str(output_path / "finqa_results_tables.tex"),
            "markdown": str(output_path / "finqa_results_summary.md"),
        }
        Path(paths["latex"]).write_text(self.render_latex(result_rows, failure_rows, diagnostic_rows), encoding="utf-8")
        Path(paths["markdown"]).write_text(
            self.render_markdown(result_rows, failure_rows, diagnostic_rows),
            encoding="utf-8",
        )
        return paths

    def render_latex(
        self,
        result_rows: list[dict[str, Any]],
        failure_rows: list[dict[str, Any]],
        diagnostic_rows: list[dict[str, Any]],
    ) -> str:
        lines = [
            "% Auto-generated by scripts/build_paper_assets.py.",
            "% Re-run after scripts/run_manifest.py --manifest configs/experiments.finqa.json.",
            "\\begin{table}[t]",
            "\\centering",
            "\\small",
            "\\begin{tabular}{llrrrrrr}",
            "\\toprule",
            "Setting & Method & EM & Ans. & Calc. & OpSem & Row & Tokens \\\\",
            "\\midrule",
        ]
        for row in result_rows:
            lines.append(
                " & ".join(
                    [
                        self._latex_escape(row["setting"]),
                        self._method_label(row["method"]),
                        self._fmt(row["accuracy"]),
                        self._fmt(row["answer_supported"]),
                        self._fmt(row["calculation_supported"]),
                        self._fmt(row["operation_semantics_checked"]),
                        self._fmt(row["row_operation_grounded"]),
                        self._fmt(row["input_tokens"]),
                    ]
                )
                + " \\\\"
            )
        lines.extend(
            [
                "\\bottomrule",
                "\\end{tabular}",
                "\\caption{FinQA 100-example diagnostic results. EM is numeric exact match. Ans., Calc., OpSem, and Row are verifier diagnostics for answer support, calculation-result support, operation-semantics checking, and row grounding. Open hybrid is a deterministic lexical/numeric reranker; source rerank uses the provided source document and is an analysis setting rather than a deployable open-retrieval claim.}",
                "\\label{tab:finqa-diagnostic-results}",
                "\\end{table}",
                "",
                "\\begin{table}[t]",
                "\\centering",
                "\\small",
                "\\begin{tabular}{lrrrrrr}",
                "\\toprule",
                "Setting & Wrong row/op & No numeric & No percent & Add./lookup & Ratio & Unsupported \\\\",
                "\\midrule",
            ]
        )
        for row in failure_rows:
            lines.append(
                " & ".join(
                    [
                        self._latex_escape(row["setting"]),
                        str(row["wrong_numeric_operation_or_row"]),
                        str(row["no_numeric_answer_other"]),
                        str(row["no_numeric_answer_percent"]),
                        str(row["no_numeric_answer_additive_or_lookup"]),
                        str(row["no_numeric_answer_ratio"]),
                        str(row["unsupported_textual_prediction"]),
                    ]
                )
                + " \\\\"
            )
        lines.extend(
            [
                "\\bottomrule",
                "\\end{tabular}",
                "\\caption{Failure categories for full EviGraph on the FinQA 100-example diagnostic subset. The categories are generated directly from the manifest CSVs and should be used to drive the next engineering iteration.}",
                "\\label{tab:finqa-failure-categories}",
                "\\end{table}",
                "",
                "\\begin{table}[t]",
                "\\centering",
                "\\small",
                "\\begin{tabular}{lrrrrrr}",
                "\\toprule",
                "Setting & Num. & Den. & Year/period & Row label & Op. type & Ambig. \\\\",
                "\\midrule",
            ]
        )
        for row in diagnostic_rows:
            lines.append(
                " & ".join(
                    [
                        self._latex_escape(row["setting"]),
                        str(row["wrong_numerator"]),
                        str(row["wrong_denominator"]),
                        str(row["wrong_year_or_period"]),
                        str(row["wrong_row_label"]),
                        str(row["wrong_operation_type"]),
                        str(row["ambiguous_supported_wrong_number"]),
                    ]
                )
                + " \\\\"
            )
        lines.extend(
            [
                "\\bottomrule",
                "\\end{tabular}",
                "\\caption{Row/operation diagnostics for wrong numeric full EviGraph answers. Counts are multi-label: one failed example can expose more than one diagnostic signal.}",
                "\\label{tab:finqa-row-operation-diagnostics}",
                "\\end{table}",
                "",
            ]
        )
        return "\n".join(lines)

    def render_markdown(
        self,
        result_rows: list[dict[str, Any]],
        failure_rows: list[dict[str, Any]],
        diagnostic_rows: list[dict[str, Any]],
    ) -> str:
        lines = [
            "# FinQA Paper Assets",
            "",
            "Generated from `outputs/eval/finqa` after the latest manifest run.",
            "",
            "## Main Diagnostic Table",
            "",
            "| setting | method | EM | answer supported | calculation supported | operation semantics | row grounded | tokens |",
            "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |",
        ]
        for row in result_rows:
            lines.append(
                "| "
                + " | ".join(
                    [
                        row["setting"],
                        row["method"],
                        self._fmt(row["accuracy"]),
                        self._fmt(row["answer_supported"]),
                        self._fmt(row["calculation_supported"]),
                        self._fmt(row["operation_semantics_checked"]),
                        self._fmt(row["row_operation_grounded"]),
                        self._fmt(row["input_tokens"]),
                    ]
                )
                + " |"
            )
        lines.extend(
            [
                "",
                "## Full EviGraph Failure Categories",
                "",
                "| setting | wrong row/op | no numeric | no percent | additive/lookup | ratio | unsupported |",
                "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
            ]
        )
        for row in failure_rows:
            lines.append(
                "| "
                + " | ".join(
                    [
                        row["setting"],
                        str(row["wrong_numeric_operation_or_row"]),
                        str(row["no_numeric_answer_other"]),
                        str(row["no_numeric_answer_percent"]),
                        str(row["no_numeric_answer_additive_or_lookup"]),
                        str(row["no_numeric_answer_ratio"]),
                        str(row["unsupported_textual_prediction"]),
                    ]
                )
                + " |"
            )
        lines.extend(
            [
                "",
                "## Row/Operation Diagnostics",
                "",
                "| setting | wrong numerator | wrong denominator | wrong year/period | wrong row label | wrong operation type | ambiguous |",
                "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
            ]
        )
        for row in diagnostic_rows:
            lines.append(
                "| "
                + " | ".join(
                    [
                        row["setting"],
                        str(row["wrong_numerator"]),
                        str(row["wrong_denominator"]),
                        str(row["wrong_year_or_period"]),
                        str(row["wrong_row_label"]),
                        str(row["wrong_operation_type"]),
                        str(row["ambiguous_supported_wrong_number"]),
                    ]
                )
                + " |"
            )
        lines.extend(
            [
                "",
                "## Paper-Safe Claims",
                "",
                "- Treat these as diagnostic smoke-subset results, not final benchmark claims.",
                "- Report open BM25 and open hybrid separately from oracle-doc and source-rerank settings.",
                "- Use the failure-category table to justify the next row/operation-selection iteration.",
                "",
            ]
        )
        return "\n".join(lines)

    def _result_rows(self, eval_dir: Path) -> list[dict[str, Any]]:
        rows = []
        for spec in DEFAULT_RESULT_SPECS:
            grouped = self._group_by_method(self._read_csv(eval_dir / spec.csv_name))
            for method in spec.methods:
                method_rows = grouped.get(method, [])
                if not method_rows:
                    continue
                rows.append(
                    {
                        "setting": spec.label,
                        "method": method,
                        "accuracy": self._mean(method_rows, "accuracy"),
                        "answer_supported": self._mean(method_rows, "answer_supported"),
                        "calculation_supported": self._mean(method_rows, "calculation_supported"),
                        "operation_semantics_checked": self._mean(method_rows, "operation_semantics_checked"),
                        "row_operation_grounded": self._mean(method_rows, "row_operation_grounded"),
                        "input_tokens": self._mean(method_rows, "input_tokens"),
                    }
                )
        return rows

    def _failure_rows(self, eval_dir: Path) -> list[dict[str, Any]]:
        rows = []
        analyzer = FailureAnalyzer()
        for spec in DEFAULT_RESULT_SPECS:
            analysis = analyzer.analyze(eval_dir / spec.csv_name, method="full_evigraph")
            categories = analysis["categories"]
            rows.append(
                {
                    "setting": spec.label,
                    "wrong_numeric_operation_or_row": categories.get("wrong_numeric_operation_or_row", 0),
                    "no_numeric_answer_other": categories.get("no_numeric_answer_other", 0),
                    "no_numeric_answer_percent": categories.get("no_numeric_answer_percent", 0),
                    "no_numeric_answer_additive_or_lookup": categories.get("no_numeric_answer_additive_or_lookup", 0),
                    "no_numeric_answer_ratio": categories.get("no_numeric_answer_ratio", 0),
                    "unsupported_textual_prediction": categories.get("unsupported_textual_prediction", 0),
                }
            )
        return rows

    def _diagnostic_rows(self, eval_dir: Path) -> list[dict[str, Any]]:
        rows = []
        analyzer = RowOperationDiagnosticAnalyzer()
        for spec in DEFAULT_RESULT_SPECS:
            analysis = analyzer.analyze(eval_dir / spec.csv_name, method="full_evigraph")
            label_counts = analysis["label_counts"]
            row = {"setting": spec.label}
            for label in DIAGNOSTIC_LABELS:
                row[label] = label_counts.get(label, 0)
            rows.append(row)
        return rows

    def _read_csv(self, path: Path) -> list[dict[str, str]]:
        if not path.exists():
            raise FileNotFoundError(f"Required experiment CSV not found: {path}")
        with path.open("r", encoding="utf-8", newline="") as handle:
            return list(csv.DictReader(handle))

    def _group_by_method(self, rows: list[dict[str, str]]) -> dict[str, list[dict[str, str]]]:
        grouped: dict[str, list[dict[str, str]]] = {}
        for row in rows:
            grouped.setdefault(row.get("method", ""), []).append(row)
        return grouped

    def _mean(self, rows: list[dict[str, str]], metric: str) -> float:
        return mean(self._to_float(row.get(metric)) for row in rows)

    def _to_float(self, value: Any) -> float:
        if value in (None, ""):
            return 0.0
        if isinstance(value, str) and value.lower() in {"true", "false"}:
            return float(value.lower() == "true")
        return float(value)

    def _fmt(self, value: float) -> str:
        return f"{value:.2f}"

    def _method_label(self, method: str) -> str:
        labels = {
            "topk": "Top-k",
            "utility_only": "Utility-only",
            "full_evigraph": "Full EviGraph",
        }
        return labels.get(method, self._latex_escape(method))

    def _latex_escape(self, text: str) -> str:
        return text.replace("&", "\\&").replace("_", "\\_")
